In [ ]:
import os
import cv2
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

# Function to extract frames from a video file
def extract_frames(video_path, frame_rate, target_size=(224, 224)):
    cap = cv2.VideoCapture(video_path)
    frames = []
    frame_count = 0

    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret==True:
            if frame_count % frame_rate == 0:
                resized_frame = cv2.resize(frame, target_size)
                frames.append(resized_frame)

            frame_count += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

    return frames

# Function to extract frames from all video files in a directory
def extract_frames_from_videos(video_directory, frame_rate, target_size=(224, 224)):
    frames_list = []
    for file in os.listdir(video_directory):
        #print("hello")
        if file.endswith('.mp4'):
            print("hello")
            video_path = os.path.join(video_directory, file)
            frames = extract_frames(video_path, frame_rate, target_size)
            print()
            frames_list.append(frames)

    return frames_list

train_dataset_dir = r'C:/Users/rineesha/Documents/Project/train2/Sony'
#print("hello")
frame_rate = 30
frames_list = extract_frames_from_videos(train_dataset_dir, frame_rate)
#print("hello")
train_data_dir = r'C:/Users/rineesha/Documents/Project/directory_Sony'
#print("hello")
for video_frames in frames_list:
    for i, frame in enumerate(video_frames):
        print(frame)
        file_path = os.path.join(train_data_dir, f'frame_{i}.jpg')
        cv2.imwrite(file_path, frame)

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

hello

[[[112  55  28]
  [112  55  28]
  [112  55  28]
  ...
  [202 164 132]
  [201 163 131]
  [201 163 131]]

 [[112  55  28]
  [112  55  28]
  [112  55  28]
  ...
  [202 164 132]
  [201 163 131]
  [201 163 131]]

 [[112  55  28]
  [112  55  28]
  [112  55  28]
  ...
  [202 164 132]
  [201 163 131]
  [201 163 131]]

 ...

 [[156 124 109]
  [154 122 106]
  [153 110  88]
  ...
  [178 134 108]
  [181 137 111]
  [193 149 123]]

 [[155 124 109]
  [153 120 104]
  [149 106  84]
  ...
  [179 133 105]
  [184 139 110]
  [187 142 113]]

 [[155 123 109]
  [149 117 101]
  [147 104  82]
  ...
  [177 132 103]
  [17